_user_langs: dict[str, str] = {}


def get_lang(user_id: int) -> str:
    return _user_langs.get(str(user_id), "en")


def set_lang(user_id: int, lang: str):
    _user_langs[str(user_id)] = lang


FA = {
    "menu_title": "🚀 *ربات ارز دیجیتال v2*\n\nهمه‌کاره ارزهای دیجیتال.\nاز منوی زیر استفاده کن یا /help را بزن.\n\n✨ *جدید:* دستیار هوش مصنوعی رایگان!",
    "price": "💰 قیمت",
    "fng": "😱 ترس و طمع",
    "news": "📰 اخبار",
    "whale": "🐋 نهنگ‌ها",
    "gas": "⛽ کارمزد",
    "wallet": "👁 رصد ولت",
    "ai": "🤖 هوش مصنوعی",
    "back": "🔙 برگشت",
    "refresh": "🔄 تازه کردن",
    "help_title": "📚 *دستورات*\n\n",
    "help_price": "`/price btc eth` — قیمت لحظه‌ای\n",
    "help_alert": "`/alert btc above 70000` — هشدار قیمت\n",
    "help_fng": "`/fng` — شاخص ترس و طمع\n",
    "help_news": "`/news 5` — اخبار انگلیسی\n",
    "help_fnews": "`/fnews 5` — اخبار فارسی\n",
    "help_whale": "`/whale` — تراکنش‌های بزرگ\n",
    "help_gas": "`/gas` — کارمزد اتریوم\n",
    "help_wallet": "`/watch 0x...` / `/wallets` — رصد ولت\n",
    "help_ask": "`/ask what is eth` — دستیار هوش مصنوعی\n",
    "help_watch": "`/watch 0x...` — رصد تراکنش‌های ولت\n",
    "live_prices": "💰 *قیمت‌های لحظه‌ای*\n",
    "custom_coins": "\nمثال: `/price btc eth`",
    "fng_title": "😱 *شاخص ترس و طمع*\n",
    "fng_7days": "📊 *۷ روز اخیر:*",
    "news_title": "📰 *آخرین اخبار*\n",
    "whale_title": "🐋 *تراکنش‌های نهنگ‌ها*\n",
    "whale_none": "تراکنش بزرگی یافت نشد.",
    "whale_error": "کلید Etherscan تنظیم نشده.\nدریافت کلید: etherscan.io/myapikey",
    "gas_title": "⛽ *کارمزد اتریوم*\n\n",
    "gas_safe": "🐢 کند:",
    "gas_normal": "🚶 معمولی:",
    "gas_fast": "🚀 سریع:",
    "wallet_title": "👁 *رصد ولت*\n\n",
    "wallet_add": "`/watch 0x... [network]` — افزودن ولت\n",
    "wallet_remove": "`/unwatch 0x... [network]` — حذف\n",
    "wallet_list": "`/wallets` — مشاهده همه\n",
    "wallet_check": "`/check` — چک دستی\n",
    "ai_title": "🤖 *دستیار هوش مصنوعی*\n\n",
    "ai_desc": "قدرت گرفته از FreeModel.dev (رایگان).\n\n",
    "ai_usage": "روش استفاده: `/ask what is DeFi?`\nمثال: `/ask اتریوم چیست؟`",
    "ai_not_configured": "هوش مصنوعی تنظیم نشده.\n`FREEMODEL_API_KEY` را در .env تنظیم کن",
    "ai_thinking": "🤔 در حال فکر کردن...",
    "ai_error": "خطا:",
    "price_usage": "روش استفاده: `/price btc eth sol`\nمثال: `/price bitcoin ethereum solana`",
    "price_error": "خطا در دریافت قیمت‌ها.",
    "price_none": "اطلاعاتی یافت نشد.",
    "alert_usage": "روش استفاده: `/alert btc above 70000`\nمثال: `/alert bitcoin above 70000`",
    "alert_direction": "از `above` یا `below` استفاده کن.",
    "alert_invalid": "قیمت نامعتبر.",
    "alert_error": "خطا در دریافت قیمت.",
    "alert_not_found": "سکه `{}` یافت نشد.",
    "alert_triggered": "⚠️ *هشدار فعال شد!*\n{} ${:,.2f} {} ${:,.2f}",
    "alert_not_triggered": "{} ${:,.2f} است. هنوز {} ${:,.2f} نشده.",
    "fng_error": "خطا در دریافت شاخص ترس و طمع.",
    "news_none": "خبری یافت نشد.",
    "portfolio_added": "✅ {} {} به سبد اضافه شد.",
    "portfolio_removed": "✅ {} از سبد حذف شد.",
    "portfolio_not_found": "{} در سبد وجود ندارد.",
    "add_usage": "روش استفاده: `/add bitcoin 0.5`",
    "remove_usage": "روش استفاده: `/remove bitcoin`",
    "add_invalid": "مقدار نامعتبر.",
    "whale_scanning": "🐋 در حال جستجو...",
    "gas_fetching": "⛽ در حال دریافت...",
    "lang_set": "🌐 زبان به فارسی تغییر کرد.",
    "lang_en": "🌐 زبان انگلیسی شد.",
    "watch_usage": "روش استفاده: `/watch 0x... [network]`\nآدرس ولت را وارد کن تا تراکنش‌هایش رصد بشه.\nاگر شبکه مشخص نکنی، روی همه شبکه‌های قابل پشتیبانی اضافه میشه.\n\nمثال: `/watch 0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18 eth`\nمثال: `/watch 0x... all`",
    "watch_invalid": "❌ آدرس نامعتبر. آدرس اتریوم باید با `0x` شروع بشه و ۴۲ کاراکتر باشه.",
    "watch_exists": "⚠️ این آدرس قبلاً اضافه شده.",
    "watch_added": "✅ ✅ آدرس `{}` با موفقیت به لیست رصد اضافه شد.\n\nاز این به بعد هر تراکنش جدیدی روی این ولت انجام بشه، اینجا بهت خبر می‌دم 🔔",
    "unwatch_usage": "روش استفاده: `/unwatch 0x...`\nمثال: `/unwatch 0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18`",
    "unwatch_done": "✅ آدرس `{}` از لیست رصد حذف شد.",
    "watch_not_found": "❌ این آدرس در لیست رصدت نیست.",
    "wallets_title": "👁 *ولت‌های تحت رصد:*\n",
    "wallets_empty": "📭 هیچ ولتی رصد نمی‌شه.\nبرای افزودن: `/watch 0x...`",
    "watch_bad_chain": "❌ شبکه نامعتبر. شبکه‌های قابل پشتیبانی:\n",
    "watch_notification": "🔔 *تراکنش جدید*\n\n📋 هش: `{}`\n💵 مقدار: `{}` (${:,.2f})\n📤 از: `{}`\n📥 به: `{}`\n🔗 [مشاهده در اتراسکن](https://etherscan.io/tx/{})",
}

EN = {
    "menu_title": "🚀 *Crypto Bot v2*\n\nYour all-in-one cryptocurrency companion.\nUse the menu below or type /help.\n\n✨ *New:* Free AI assistant!",
    "price": "💰 Price",
    "fng": "😱 F&G Index",
    "news": "📰 News",
    "whale": "🐋 Whale Alert",
    "gas": "⛽ Gas Fee",
    "wallet": "👁 Wallet",
    "ai": "🤖 AI Assistant",
    "back": "🔙 Back",
    "refresh": "🔄 Refresh",
    "help_title": "📚 *Commands*\n\n",
    "help_price": "`/price btc eth` — current prices\n",
    "help_alert": "`/alert btc above 70000` — price check\n",
    "help_fng": "`/fng` — Fear & Greed Index\n",
    "help_news": "`/news 5` — English news\n",
    "help_fnews": "`/fnews 5` — اخبار فارسی\n",
    "help_whale": "`/whale` — large transactions\n",
    "help_gas": "`/gas` — Ethereum gas fees\n",
    "help_wallet": "`/watch 0x...` / `/wallets` — monitor wallets\n",
    "help_ask": "`/ask what is eth` — AI assistant\n",
    "help_watch": "`/watch 0x...` — monitor wallet txs\n",
    "live_prices": "💰 *Live Prices*\n",
    "custom_coins": "\nTry: `/price btc eth`",
    "fng_title": "😱 *Fear & Greed Index*\n",
    "fng_7days": "📊 *Last 7 days:*",
    "news_title": "📰 *Latest News*\n",
    "whale_title": "🐋 *Whale Transactions*\n",
    "whale_none": "No large transactions found.",
    "whale_error": "Set `ETHERSCAN_API_KEY` in .env\nGet one: etherscan.io/myapikey",
    "gas_title": "⛽ *Ethereum Gas Fees*\n\n",
    "gas_safe": "🐢 Safe:",
    "gas_normal": "🚶 Normal:",
    "gas_fast": "🚀 Fast:",
    "wallet_title": "👁 *Wallet Monitor*\n\n",
    "wallet_add": "`/watch 0x... [network]` — add wallet\n",
    "wallet_remove": "`/unwatch 0x... [network]` — remove\n",
    "wallet_list": "`/wallets` — list all\n",
    "wallet_check": "`/check` — manual scan\n",
    "ai_title": "🤖 *AI Assistant*\n\n",
    "ai_desc": "Powered by FreeModel.dev (free).\n\n",
    "ai_usage": "Usage: `/ask what is DeFi?`\nExample: `/ask explain blockchain`",
    "ai_not_configured": "AI is not configured.\nSet `FREEMODEL_API_KEY` in .env",
    "ai_thinking": "🤔 Thinking...",
    "ai_error": "Error:",
    "price_usage": "Usage: `/price btc eth sol`\nExample: `/price bitcoin ethereum solana`",
    "price_error": "Error fetching prices.",
    "price_none": "No data found.",
    "alert_usage": "Usage: `/alert btc above 70000`\nExample: `/alert bitcoin above 70000`",
    "alert_direction": "Use `above` or `below`.",
    "alert_invalid": "Invalid price.",
    "alert_error": "Error fetching price.",
    "alert_not_found": "Coin `{}` not found.",
    "alert_triggered": "⚠️ *Alert triggered!*\n{} ${:,.2f} {} ${:,.2f}",
    "alert_not_triggered": "{} ${:,.2f}. Not {} ${:,.2f} yet.",
    "fng_error": "Error fetching Fear & Greed Index.",
    "news_none": "No news found.",
    "portfolio_added": "✅ Added {} {} to portfolio.",
    "portfolio_removed": "✅ Removed {} from portfolio.",
    "portfolio_not_found": "{} not in portfolio.",
    "add_usage": "Usage: `/add bitcoin 0.5`",
    "remove_usage": "Usage: `/remove bitcoin`",
    "add_invalid": "Invalid amount.",
    "whale_scanning": "🐋 Scanning...",
    "gas_fetching": "⛽ Fetching...",
    "lang_set": "🌐 Language set to English.",
    "lang_fa": "🌐 زبان به فارسی تغییر کرد.",
    "watch_usage": "Usage: `/watch 0x... [network]`\nMonitor a wallet address across one or all supported networks.\nIf no network specified, adds to all chains.\n\nExample: `/watch 0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18 eth`\nExample: `/watch 0x... all`",
    "watch_invalid": "❌ Invalid address. Ethereum address must start with `0x` and be 42 characters.",
    "watch_exists": "⚠️ This address is already being watched.",
    "watch_added": "✅ Address `{}` added to watchlist.\n\nI'll notify you here whenever a new transaction occurs on this wallet 🔔",
    "unwatch_usage": "Usage: `/unwatch 0x...`\nExample: `/unwatch 0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18`",
    "unwatch_done": "✅ Address `{}` removed from watchlist.",
    "watch_not_found": "❌ This address is not in your watchlist.",
    "wallets_title": "👁 *Watched Wallets:*\n",
    "wallets_empty": "📭 No wallets being watched.\nTo add: `/watch 0x...`",
    "watch_bad_chain": "❌ Invalid chain. Supported chains:\n",
    "watch_notification": "🔔 *New Transaction*\n\n📋 Hash: `{}`\n💵 Value: `{}` (${:,.2f})\n📤 From: `{}`\n📥 To: `{}`\n🔗 [View on Etherscan](https://etherscan.io/tx/{})",
}
